### ISSUE TITLE
Wg0 can't  start - Table does not exist (do you need to insmod?) Perhaps ip6tables or your kernel needs to be upgraded.

### ISSUE THREAD

**Issue by DJIronic** [perara/wg-manager#130]
**Describe the bug**
I wanted to change an endpoint domain. I was unable to edit tge wg0, so I deleted in and created it again with the new domain on ednpoint. But now my wg0 server will not start.

**To Reproduce**
Add and remove a server and try to start it.

**Platform:**
 - OS: Docker on Ubuntu 20.04.4 LTS
 - Chrome with Adblock disabled
 - I pulled the newst image today a part of debug process

**Stacktrace/error output**
Log form docker container when I click the start button:
`wg-manager   | b"[#] ip link add wg0 type wireguard\n[#] wg setconf wg0 /dev/fd/63\n[#] ip -4 address add 10.0.200.1/24 dev wg0\n[#] ip -6 address add fd42:42:42::1/64 dev wg0\n[#] ip link set mtu 1420 up dev wg0\n[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;\nmodprobe: FATAL: Module ip6_tables not found in directory /lib/modules/5.4.0-104-generic\nip6tables v1.8.4 (legacy): can't initialize ip6tables table 'filter': Table does not exist (do you need to insmod?)\nPerhaps ip6tables or your kernel needs to be upgraded.\n[#] ip link delete dev wg0\n"`

**Additional context**
I tried disabling IPv6, asi I dont have it on the server at all.

**Screenshots**
![image](https://user-images.githubusercontent.com/9658012/157957856-a5eb65c3-8f6b-4814-b8db-c1febdce5c53.png)

**Comment by outbackdingo** [comment]
just hit exactly the same error here

**Comment by outbackdingo** [comment]
root@vpn:~# sudo modprobe ip6_tables

and fixed!

**Comment by perara** [comment]
Perhaps thjis can be fixed with issuing modprobe from the docker if ip6_tables is not found.

**Comment by liviom** [comment]
after upgrading from ubuntu 23.04 to 23.10 i had exactly the same error,
switching back to 23.04 all works.

I paste the error in the log of the container


`[2023-12-08 08:43:42 +0000] [9] [INFO] Starting gunicorn 20.0.4
[2023-12-08 08:43:42 +0000] [9] [INFO] Listening at: http://0.0.0.0:8888 (9)
[2023-12-08 08:43:42 +0000] [9] [INFO] Using worker: uvicorn.workers.UvicornWorker
[2023-12-08 08:43:42 +0000] [11] [INFO] Booting worker with pid: 11
loglevel=info workers=1 bind=0.0.0.0:8888 worker-tmp-dir=/dev/shm workers_per_core=1 host=0.0.0.0 port=8888 
0 -> 1... 
0 -> 1... 
done
done
1 -> 2... 
1 -> 2... 
done
done
2 -> 3... 
2 -> 3... 
done
done
3 -> 4... 
3 -> 4... 
done
done
4 -> 5... 
4 -> 5... 
done
done
5 -> 6... 
5 -> 6... 
done
done
6 -> 7... 
6 -> 7... 
done
done
7 -> 8... 
7 -> 8... 
done
done
8 -> 9... 
8 -> 9... 
done
done
9 -> 10... 
9 -> 10... 
done
done
10 -> 11... 
10 -> 11... 
done
done
[2023-12-08 08:43:43 +0000] [11] [INFO] Started server process [11]
[2023-12-08 08:43:43 +0000] [11] [INFO] Waiting for application startup.
Started server process [11]
Started server process [11]
Waiting for application startup.
Waiting for application startup.
[2023-12-08 08:43:43 +0000] [11] [INFO] Application startup complete.
Application startup complete.
Application startup complete.
192.168.0.97:59919 - "GET / HTTP/1.1" 200
192.168.0.97:59919 - "GET / HTTP/1.1" 200
192.168.0.97:59919 - "GET /styles.5c17e37286d14c771ea6.css HTTP/1.1" 200
192.168.0.97:59919 - "GET /styles.5c17e37286d14c771ea6.css HTTP/1.1" 200
192.168.0.97:59918 - "GET /runtime-es2015.45b4bbe7850d7279dd29.js HTTP/1.1" 200
192.168.0.97:59918 - "GET /runtime-es2015.45b4bbe7850d7279dd29.js HTTP/1.1" 200
192.168.0.97:59920 - "GET /polyfills-es2015.955abfefaaaee8e8cf75.js HTTP/1.1" 200
192.168.0.97:59920 - "GET /polyfills-es2015.955abfefaaaee8e8cf75.js HTTP/1.1" 200
192.168.0.97:59921 - "GET /main-es2015.92c7644eaefdc2f92841.js HTTP/1.1" 200
192.168.0.97:59921 - "GET /main-es2015.92c7644eaefdc2f92841.js HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto.31d6cfe0d16ae931b73c.ttf HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto.31d6cfe0d16ae931b73c.ttf HTTP/1.1" 200
192.168.0.97:59921 - "GET /5-es2015.cdaff20e03f58be99d20.js HTTP/1.1" 200
192.168.0.97:59921 - "GET /5-es2015.cdaff20e03f58be99d20.js HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto.31d6cfe0d16ae931b73c.woff2 HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto.31d6cfe0d16ae931b73c.woff2 HTTP/1.1" 200
192.168.0.97:59921 - "GET /MaterialIcons-Regular.3ca2d0e0533b7cc7583c.woff2 HTTP/1.1" 200
192.168.0.97:59921 - "GET /MaterialIcons-Regular.3ca2d0e0533b7cc7583c.woff2 HTTP/1.1" 200
192.168.0.97:59919 - "GET /Roboto.31d6cfe0d16ae931b73c.woff HTTP/1.1" 200
192.168.0.97:59919 - "GET /Roboto.31d6cfe0d16ae931b73c.woff HTTP/1.1" 200
192.168.0.97:59921 - "GET /assets/icons/favicon-32x32.png HTTP/1.1" 200
192.168.0.97:59921 - "GET /assets/icons/favicon-32x32.png HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/login HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/login HTTP/1.1" 200
192.168.0.97:59919 - "GET /Roboto-Bold.31d6cfe0d16ae931b73c.ttf HTTP/1.1" 200
192.168.0.97:59919 - "GET /Roboto-Bold.31d6cfe0d16ae931b73c.ttf HTTP/1.1" 200
192.168.0.97:59921 - "GET /api/v1/server/all HTTP/1.1" 200
192.168.0.97:59921 - "GET /api/v1/server/all HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto-Bold.31d6cfe0d16ae931b73c.woff2 HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto-Bold.31d6cfe0d16ae931b73c.woff2 HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto-Bold.31d6cfe0d16ae931b73c.woff HTTP/1.1" 200
192.168.0.97:59921 - "GET /Roboto-Bold.31d6cfe0d16ae931b73c.woff HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/add HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/add HTTP/1.1" 200
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
b"[#] ip link add wg0 type wireguard\n[#] wg setconf wg0 /dev/fd/63\n[#] ip -4 address add 10.0.200.1/24 dev wg0\n[#] ip -6 address add fd42:42:42::1/64 dev wg0\n[#] ip link set mtu 1420 up dev wg0\n[#] iptables -A FORWARD -i wg0 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;ip6tables -A FORWARD -i wg0 -j ACCEPT; ip6tables -t nat -A POSTROUTING -o eth0 -j MASQUERADE;\nmodprobe: FATAL: Module ip6_tables not found in directory /lib/modules/6.5.0-14-generic\nip6tables v1.8.4 (legacy): can't initialize ip6tables table `filter': Table does not exist (do you need to insmod?)\nPerhaps ip6tables or your kernel needs to be upgraded.\n[#] ip link delete dev wg0\n"
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/delete HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/delete HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/add HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/add HTTP/1.1" 200
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
Exception in callback Loop._read_from_self
handle: <Handle Loop._read_from_self>
Traceback (most recent call last):
  File "uvloop/cbhandles.pyx", line 66, in uvloop.loop.Handle._run
  File "uvloop/loop.pyx", line 390, in uvloop.loop.Loop._read_from_self
  File "uvloop/loop.pyx", line 395, in uvloop.loop.Loop._invoke_signals
  File "uvloop/loop.pyx", line 370, in uvloop.loop.Loop._ceval_process_signals
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 242, in handle_chld
    self.reap_workers()
  File "/usr/lib/python3/dist-packages/gunicorn/arbiter.py", line 525, in reap_workers
    raise HaltServer(reason, self.WORKER_BOOT_ERROR)
gunicorn.errors.HaltServer: <HaltServer 'Worker failed to boot.' 3>
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/start HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/delete HTTP/1.1" 200
192.168.0.97:59921 - "POST /api/v1/server/delete HTTP/1.1" 200
`
