### ISSUE TITLE
running "uvicorn main:app --host=0.0.0.0" fails

### ISSUE THREAD

**Issue by 2L3R4** [perara/wg-manager#6]
I copied all commands from [install.md](https://github.com/perara/wg-manager/blob/master/docs/install.md), it only failed on the last command.
the only thing I changed was the PORT from 80 to 8888
expected output: (something like)
`#INFO:     Started server process [259296]  
#INFO:     Waiting for application startup.  
#INFO:     Application startup complete.  
#INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)   `
actual output:
`Traceback (most recent call last):  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/repository.py", line 95, in verify  
    cls.require_found(os.path.join(path, cls._config))  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/pathed.py", line 72, in require_found  
    raise exceptions.PathNotFoundError(path)  
migrate.exceptions.PathNotFoundError: migrations/migrate.cfg  
  
During handling of the above exception, another exception occurred:  
  
Traceback (most recent call last):  
  File "/opt/wg-manager/wg_dashboard_backend/venv/bin/uvicorn", line 8, in <module>  
    sys.exit(main())  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/click/core.py",   line 829, in __call__  
    return self.main(*args, **kwargs)  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/click/core.py",   line 782, in main  
    rv = self.invoke(ctx)  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/click/core.py",   line 1066, in invoke  
    return ctx.invoke(self.callback, **ctx.params)  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/click/core.py",   line 610, in invoke  
    return callback(*args, **kwargs)  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/uvicorn/main.py", line 331, in main  
    run(**kwargs)  
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/uvicorn/main.py", line 354, in run  
    server.run()
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/uvicorn/main.py", line 382, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "uvloop/loop.pyx", line 1456, in uvloop.loop.Loop.run_until_complete
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/uvicorn/main.py", line 389, in serve
    config.load()
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/uvicorn/config.py", line 288, in load
    self.loaded_app = import_from_string(self.app)
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./main.py", line 8, in <module>
    import middleware
  File "./middleware.py", line 14, in <module>
    import schemas
  File "./schemas.py", line 6, in <module>
    import models
  File "./models.py", line 5, in <module>
    from database import Base
  File "./database.py", line 19, in <module>
    main(["version_control", DATABASE_URL, "migrations"])
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/shell.py", line 209, in main
    ret = command_func(**kwargs)
  File "<decorator-gen-8>", line 2, in version_control
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/util/__init__.py", line 167, in with_engine
    return f(*a, **kw)
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/api.py", line 250, in version_control
    ControlledSchema.create(engine, repository, version)
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/schema.py", line 139, in create
    repository = Repository(repository)
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/repository.py", line 77, in __init__
    self.verify(path)
  File "/opt/wg-manager/wg_dashboard_backend/venv/lib/python3.8/site-packages/migrate/versioning/repository.py", line 98, in verify
    raise exceptions.InvalidRepositoryError(path)
migrate.exceptions.InvalidRepositoryError: migrations`

**Comment by perara** [comment]
Hi. Please try to pull latest changes. I forgot to add a few files to the git tree. sorry!

**Comment by 2L3R4** [comment]
I deleted the directory and started over; still not working; how I understand this error it says there is `migrations/migrate.cfg`missing; what should be in that file?

**Comment by perara** [comment]
Very sorry!
I forgot to actually push the changes. The files(s) should be present now!

**Comment by 2L3R4** [comment]
now the old error is gone, but a new error appeared:

`sqlalchemy.exc.NoSuchTableError: server`  (see attached log)

[log.log](https://github.com/perara/wg-manager/files/4495081/log.log)

**Comment by Zhmakda** [comment]
I have same problem
`sqlalchemy.exc.NoSuchTableError: server`
during uvicorn main:app --host=0.0.0.0

Here install log from "Building front-end" section
[log.txt](https://github.com/perara/wg-manager/files/4520490/log.txt)

**Comment by perara** [comment]
@Zhmakda and @2L3R4. Could you retry with 91e5cc2 or newer?

**Comment by 2L3R4** [comment]
It now works (for me), but I can't login with user: admin, password: admin → new issue

**Comment by perara** [comment]
@2L3R4 - I did an additional ordering of code execution. Delete the database and retry. Everything has to go smooth during setup, else it might mess up the admin creation. I'll make this generally smoother (setup wizard) later, but as a temp solution, I found this to be OK. Test and see if 04f654e

**Comment by 2L3R4** [comment]
now there is an other error:
"AttributeError: shared_key"
full log: [log.txt](https://github.com/perara/wg-manager/files/4521277/log.txt)

**Comment by perara** [comment]
Sorry, It should work fine now if you repeat the same (delete and rerun) process.

**Comment by 2L3R4** [comment]
So, I am closing this (again) because it does now work, but now there is #9
